import type { MakeupStyle } from '@/types';

export const MOCK_STYLES: MakeupStyle[] = [
  {
    id: 'natural-glow',
    name: 'Natural Glow',
    nameZh: '自然光泽',
    description: 'A soft, dewy look that enhances your natural beauty with a luminous finish',
    category: 'natural',
    gradient: 'linear-gradient(135deg, #F5CBA7, #F0B27A, #E8A87C)',
    accentColor: '#F0B27A',
    tags: ['Daily', 'Minimal', 'Dewy'],
    defaultParams: {
      lipColor: '#D4877A',
      lipIntensity: 30,
      eyeShadowColor: '#C4A882',
      eyeShadowIntensity: 20,
      blushLevel: 35,
      contourLevel: 20,
      overallIntensity: 40,
    },
  },
  {
    id: 'smoky-evening',
    name: 'Smoky Evening',
    nameZh: '烟熏晚妆',
    description: 'Dramatic smoky eyes with deep tones perfect for evening events',
    category: 'glam',
    gradient: 'linear-gradient(135deg, #2C2C54, #474787, #706FD3)',
    accentColor: '#706FD3',
    tags: ['Evening', 'Dramatic', 'Smoky'],
    defaultParams: {
      lipColor: '#8B4557',
      lipIntensity: 60,
      eyeShadowColor: '#2C2C54',
      eyeShadowIntensity: 80,
      blushLevel: 30,
      contourLevel: 65,
      overallIntensity: 70,
    },
  },
  {
    id: 'soft-glam',
    name: 'Soft Glam',
    nameZh: '柔光魅力',
    description: 'Warm golden tones with a perfect balance of elegance and approachability',
    category: 'glam',
    gradient: 'linear-gradient(135deg, #D4A843, #C19A3E, #B8860B)',
    accentColor: '#D4A843',
    tags: ['Warm', 'Golden', 'Elegant'],
    defaultParams: {
      lipColor: '#C44040',
      lipIntensity: 55,
      eyeShadowColor: '#B8860B',
      eyeShadowIntensity: 55,
      blushLevel: 45,
      contourLevel: 50,
      overallIntensity: 60,
    },
  },
  {
    id: 'editorial-bold',
    name: 'Editorial Bold',
    nameZh: '大胆前卫',
    description: 'A striking editorial look with bold colors and sharp definition',
    category: 'editorial',
    gradient: 'linear-gradient(135deg, #C0392B, #E74C3C, #FF6B6B)',
    accentColor: '#E74C3C',
    tags: ['Bold', 'Creative', 'Statement'],
    defaultParams: {
      lipColor: '#C0392B',
      lipIntensity: 90,
      eyeShadowColor: '#1A1A2E',
      eyeShadowIntensity: 85,
      blushLevel: 40,
      contourLevel: 75,
      overallIntensity: 85,
    },
  },
  {
    id: 'romantic-rose',
    name: 'Romantic Rose',
    nameZh: '浪漫玫瑰',
    description: 'Soft pinks and rose tones for a dreamy, romantic aesthetic',
    category: 'romantic',
    gradient: 'linear-gradient(135deg, #F8B4C8, #E8A0B4, #D4878A)',
    accentColor: '#E8A0B4',
    tags: ['Romantic', 'Pink', 'Soft'],
    defaultParams: {
      lipColor: '#D4878A',
      lipIntensity: 50,
      eyeShadowColor: '#E8A0B4',
      eyeShadowIntensity: 40,
      blushLevel: 60,
      contourLevel: 30,
      overallIntensity: 50,
    },
  },
  {
    id: 'sun-kissed',
    name: 'Sun-Kissed Bronze',
    nameZh: '阳光古铜',
    description: 'A warm, bronzed look that captures the essence of golden hour',
    category: 'fresh',
    gradient: 'linear-gradient(135deg, #CD853F, #D4A06A, #DAA520)',
    accentColor: '#CD853F',
    tags: ['Bronze', 'Warm', 'Summer'],
    defaultParams: {
      lipColor: '#B87333',
      lipIntensity: 40,
      eyeShadowColor: '#CD853F',
      eyeShadowIntensity: 45,
      blushLevel: 55,
      contourLevel: 60,
      overallIntensity: 55,
    },
  },
  {
    id: 'classic-red',
    name: 'Classic Red Lip',
    nameZh: '经典红唇',
    description: 'Timeless elegance with a bold red lip and refined eye definition',
    category: 'classic',
    gradient: 'linear-gradient(135deg, #8B0000, #C41E3A, #DC143C)',
    accentColor: '#C41E3A',
    tags: ['Classic', 'Red Lip', 'Timeless'],
    defaultParams: {
      lipColor: '#C41E3A',
      lipIntensity: 85,
      eyeShadowColor: '#3C1414',
      eyeShadowIntensity: 35,
      blushLevel: 35,
      contourLevel: 45,
      overallIntensity: 65,
    },
  },
  {
    id: 'dewy-fresh',
    name: 'Dewy Fresh',
    nameZh: '清透水光',
    description: 'Ultra-fresh, glass-skin effect with barely-there makeup',
    category: 'fresh',
    gradient: 'linear-gradient(135deg, #A8E6CF, #88D8B0, #7EC8A0)',
    accentColor: '#88D8B0',
    tags: ['Fresh', 'Glass Skin', 'Minimal'],
    defaultParams: {
      lipColor: '#E0A0A0',
      lipIntensity: 20,
      eyeShadowColor: '#C4B896',
      eyeShadowIntensity: 15,
      blushLevel: 25,
      contourLevel: 15,
      overallIntensity: 30,
    },
  },
];
