'use client';

import { motion, useScroll, useTransform } from 'framer-motion';
import { useRef, useEffect, useState } from 'react';
import { useAppStore } from '@/stores/appStore';
import ImageWaterfall from './ImageWaterfall';

/* ---- Mouse-following cursor glow ---- */
function CursorGlow() {
  const [pos, setPos] = useState({ x: 0, y: 0 });
  const [visible, setVisible] = useState(false);

  useEffect(() => {
    const move = (e: MouseEvent) => {
      setPos({ x: e.clientX, y: e.clientY });
      setVisible(true);
    };
    const leave = () => setVisible(false);
    window.addEventListener('mousemove', move);
    window.addEventListener('mouseleave', leave);
    return () => {
      window.removeEventListener('mousemove', move);
      window.removeEventListener('mouseleave', leave);
    };
  }, []);

  return (
    <motion.div
      className="pointer-events-none fixed z-40"
      animate={{
        x: pos.x - 200,
        y: pos.y - 200,
        opacity: visible ? 1 : 0,
      }}
      transition={{ type: 'spring', damping: 30, stiffness: 200 }}
    >
      <div className="w-[400px] h-[400px] rounded-full bg-accent/[0.08] blur-[80px]" />
    </motion.div>
  );
}

export default function HeroSection() {
  const setStep = useAppStore((s) => s.setStep);
  const ref = useRef<HTMLDivElement>(null);
  const { scrollYProgress } = useScroll({ target: ref, offset: ['start start', 'end start'] });
  const y = useTransform(scrollYProgress, [0, 1], [0, 150]);
  const opacity = useTransform(scrollYProgress, [0, 0.6], [1, 0]);
  const scale = useTransform(scrollYProgress, [0, 1], [1, 0.95]);

  return (
    <section ref={ref} className="relative min-h-[100vh] flex flex-col items-center justify-center px-6 overflow-hidden">
      <CursorGlow />

      {/* Waterfall image background */}
      <ImageWaterfall />

      {/* Main content - above waterfall */}
      <motion.div className="relative z-20 max-w-3xl mx-auto text-center" style={{ y, opacity, scale }}>
        {/* Glass card behind text for readability */}
        <div className="relative">
          {/* Tag */}
          <motion.div
            initial={{ opacity: 0, y: 20, filter: 'blur(10px)' }}
            animate={{ opacity: 1, y: 0, filter: 'blur(0px)' }}
            transition={{ duration: 0.8, delay: 0.3, ease: [0.22, 1, 0.36, 1] as const }}
            className="mb-8"
          >
            <span className="inline-flex items-center gap-2.5 text-[13px] text-fg-secondary tracking-wide px-4 py-2 rounded-full border border-black/[0.06] bg-white/70 backdrop-blur-md shadow-sm">
              <motion.span
                className="w-2 h-2 rounded-full bg-accent"
                animate={{ scale: [1, 1.4, 1], opacity: [1, 0.6, 1] }}
                transition={{ duration: 2, repeat: Infinity }}
              />
              AI-Powered Makeup
            </span>
          </motion.div>

          {/* Headline */}
          <motion.h1
            className="text-[clamp(2.8rem,7vw,5rem)] font-semibold leading-[1.05] tracking-[-0.04em] mb-6"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 0.1, delay: 0.4 }}
          >
            <motion.span
              className="inline-block drop-shadow-[0_1px_2px_rgba(250,249,246,0.8)]"
              initial={{ opacity: 0, y: 40, filter: 'blur(12px)' }}
              animate={{ opacity: 1, y: 0, filter: 'blur(0px)' }}
              transition={{ duration: 0.8, delay: 0.5, ease: [0.22, 1, 0.36, 1] as const }}
            >
              Your next look,
            </motion.span>
            <br />
            <motion.span
              className="inline-block text-gradient-animated"
              initial={{ opacity: 0, y: 40, filter: 'blur(12px)' }}
              animate={{ opacity: 1, y: 0, filter: 'blur(0px)' }}
              transition={{ duration: 0.8, delay: 0.7, ease: [0.22, 1, 0.36, 1] as const }}
            >
              generated by AI
            </motion.span>
          </motion.h1>

          {/* Subtitle */}
          <motion.p
            className="text-fg-secondary text-lg md:text-xl leading-relaxed max-w-xl mx-auto mb-12"
            initial={{ opacity: 0, y: 30, filter: 'blur(8px)' }}
            animate={{ opacity: 1, y: 0, filter: 'blur(0px)' }}
            transition={{ duration: 0.8, delay: 0.9, ease: [0.22, 1, 0.36, 1] as const }}
          >
            Upload a selfie. Get 8 personalized makeup styles in seconds. Fine-tune until perfect.
          </motion.p>

          {/* CTA */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 1.1, ease: [0.22, 1, 0.36, 1] as const }}
            className="flex flex-col sm:flex-row items-center justify-center gap-4"
          >
            <motion.button
              className="btn-primary shimmer-btn text-[15px] px-10 py-4 group shadow-lg shadow-black/10"
              onClick={() => setStep('upload')}
              whileHover={{ scale: 1.03 }}
              whileTap={{ scale: 0.97 }}
            >
              <span className="relative z-10 flex items-center gap-2">
                Try it free
                <motion.svg
                  width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"
                  strokeLinecap="round" strokeLinejoin="round"
                  animate={{ x: [0, 3, 0] }}
                  transition={{ duration: 1.5, repeat: Infinity, ease: 'easeInOut' }}
                >
                  <path d="M5 12h14" /><path d="m12 5 7 7-7 7" />
                </motion.svg>
              </span>
            </motion.button>
            <motion.span
              className="text-fg-muted text-sm"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 1.5 }}
            >
              No sign-up required
            </motion.span>
          </motion.div>

          {/* Trust badges */}
          <motion.div
            className="mt-14 flex items-center justify-center gap-8"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 1.7, duration: 0.8 }}
          >
            {['10K+ users', '4.9 rating', 'Privacy first'].map((t, i) => (
              <motion.span
                key={t}
                className="text-xs text-fg-muted flex items-center gap-1.5 bg-white/50 backdrop-blur-sm px-3 py-1 rounded-full"
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 1.7 + i * 0.15 }}
              >
                <span className="w-1 h-1 rounded-full bg-accent/60" />
                {t}
              </motion.span>
            ))}
          </motion.div>
        </div>
      </motion.div>

      {/* Scroll cue */}
      <motion.div
        className="absolute bottom-8 left-1/2 -translate-x-1/2 z-20"
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 2.2 }}
      >
        <motion.div
          animate={{ y: [0, 8, 0] }}
          transition={{ duration: 2, repeat: Infinity, ease: 'easeInOut' }}
          className="flex flex-col items-center gap-2"
        >
          <span className="text-[10px] text-fg-muted tracking-widest uppercase bg-white/50 backdrop-blur-sm px-3 py-1 rounded-full">Scroll</span>
          <div className="w-5 h-9 rounded-full border-2 border-black/[0.15] bg-white/30 backdrop-blur-sm flex justify-center pt-2">
            <motion.div
              className="w-1 h-2 rounded-full bg-accent/70"
              animate={{ y: [0, 10, 0], opacity: [1, 0.3, 1] }}
              transition={{ duration: 2, repeat: Infinity, ease: 'easeInOut' }}
            />
          </div>
        </motion.div>
      </motion.div>
    </section>
  );
}
